print('Enter the number of coints you have.')
sum = 0
print('500 won?', end = ' ')
x = input()
sum += 500 * int(x)
print('100 won?', end = ' ')
x = input()
sum += 100 * int(x)
print('50 won?', end = ' ')
x = input()
sum += 50 * int(x)
print('10 won?', end = ' ')
x = input()
sum += 10 * int(x)
print('You have ', sum, ' won in total')
